[package]
name = "iamb"
version = "0.0.8"
edition = "2018"
authors = ["Ulyssa <git@ulyssa.dev>"]
repository = "https://github.com/ulyssa/iamb"
homepage = "https://iamb.chat"
readme = "README.md"
description = "A Matrix chat client that uses Vim keybindings"
license = "Apache-2.0"
exclude = [".github", "CONTRIBUTING.md"]
keywords = ["matrix", "chat", "tui", "vim"]
categories = ["command-line-utilities"]
rust-version = "1.66"
build = "build.rs"

[build-dependencies]
mandown = "0.1.3"

[build-dependencies.vergen]
version = "8"
default-features = false
features = ["build", "git", "gitcl",]

[dependencies]
arboard = "3.2.0"
bitflags = "1.3.2"
chrono = "0.4.26"
clap = {version = "4.3.12", features = ["derive"]}
comrak = {version = "0.18.0", features = ["shortcodes"]}
css-color-parser = "0.1.2"
dirs = "4.0.0"
emojis = "0.6.0"
futures = "0.3.28"
gethostname = "0.4.1"
html5ever = "0.26.0"
image = "0.24.5"
libc = "0.2.147"
markup5ever_rcdom = "0.2.0"
mime = "0.3.17"
mime_guess = "2.0.4"
open = "5.0.0"
regex = "1.9.1"
rpassword = "7.2.0"
serde = "1.0.171"
serde_json = "1.0.103"
thiserror = "1.0.43"
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.17"
unicode-segmentation = "1.10.1"
unicode-width = "0.1.10"
url = {version = "2.4.0", features = ["serde"]}

[dependencies.modalkit]
version = "0.0.16"

[dependencies.matrix-sdk]
version = "0.6"
default-features = false
features = ["e2e-encryption", "sled", "rustls-tls"]

[dependencies.tokio]
version = "1.29.1"
features = ["macros", "net", "rt-multi-thread", "sync", "time"]

[dev-dependencies]
lazy_static = "1.4.0"
pretty_assertions = "1.4.0"

[profile.release]
lto = true
incremental = false
